# Generated by Django 3.0.5 on 2020-06-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='period',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=200, null=True),
        ),
    ]
