# Generated by Django 3.0.5 on 2020-06-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0009_auto_20200629_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
